apiVersion: v1
kind: Pod
metadata:
 name: mysql
 labels:
   app: wordpress
spec:
 containers:
   - image: mysql:5.6
     name: mysql
     env:
     - name: MYSQL_ROOT_PASSWORD
       value: 1414nikhil
     - name: MYSQL_DATABASE
       value: nik
     ports:
     - containerPort: 3306
